# Main composition file for SIG Application Container.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore
# Capacitação Redes - PV Intelbras

version: '3.8'
services:
  radioanalyser:
    container_name: radioanalyser
    ports:
      - '1025:22' # sshservice port
    volumes:
      - "/dev/:/dev/"
      - "./out/:/outputfiles/"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    privileged: true
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - "DISPLAY=$DISPLAY"